---
# Configure Deployment Server

# Configure indexes to use with deployment cluster Master.
# The file will be created on the Deployment server and then pushed to the CM
# From the CM a process will run to deploy out to the indexers

- name: "Create {{ org_prefix }}_indexer_volume_indexes app directory"
  file:
    path: "{{ splunk_base }}/etc/deployment-apps/{{ org_prefix }}_indexer_volume_indexes/local/"
    owner: splunk
    group: splunk
    mode: u=rwX,g=rX,o-rwx
    recurse: yes
    state: directory

- name: "Create {{ org_prefix }}_indexer_volume_indexes app.conf for deployment"
  copy:
    content: |
      [install]
      state = enabled

      [package]
      check_for_updates = false

      [ui]
      is_visible = false
      is_manageable = false
    dest: "{{ splunk_base }}/etc/deployment-apps/{{ org_prefix }}_indexer_volume_indexes/local/app.conf"
    owner: splunk
    group: splunk
    mode: u=rwX,g=rX,o-rwx

- name: "Create {{ org_prefix }}_indexer_volume_indexes indexes.conf for deployment"
  copy:
    content: |
      [volume:primary]
      maxVolumeDataSizeMB = {{ idx_primary_maxVolumeDataSizeMB }}
      path = {{ idx_primary_path }}

      [volume:secondary]
      maxVolumeDataSizeMB = {{ idx_secondary_maxVolumeDataSizeMB }}
      path = {{ idx_secondary_path }}
    dest: "{{ splunk_base }}/etc/deployment-apps/{{ org_prefix }}_indexer_volume_indexes/local/indexes.conf"
    owner: splunk
    group: splunk
    mode: u=rwX,g=rX,o-rwx
