---
# Installing common packages with one task
- name: install required packages using the apt module
  apt:
    name: "{{ packages }}"
    update_cache: yes
    cache_valid_time: 3600
  vars:
    packages:
      - 'python3'
      - 'python3-openssl'
      - 'python3-pip'
      - 'python-pip'
      - 'python-openssl'
      - 'vim-nox'
      - 'tmux'
      - 'tree'
  ignore_errors: True

- name: Install common utils using Pip
  pip:
    name: "{{ pip_packages }}"
    executable: pip3
  vars:
    pip_packages:
      - 'boto3'
      - 'awscli'
      - 'python-dateutil'
  ignore_errors: True

- name: Create 00-PreserveFQDN rsyslog setting file
  copy:
    content: |
      # Log FQDN always
      $PreserveFQDN on
    dest: "/etc/rsyslog.d/00-PreserveFQDN.conf"
    owner: root
    group: root
    mode: '0644'