---
# Installing common packages with one task
- name: install required packages using the apt module
  apt:
    name: "{{ item }}"
    update_cache: yes
  with_items:
    - 'python3'
    - 'python3-openssl'
    - 'python3-pip'
    - 'python-pip'
    - 'python-openssl'
    - 'vim-nox'
    - 'tmux'
    - 'nmap'
    - 'tree'
  ignore_errors: True

- name: Install common utils using Pip
  pip:
    name: boto3 awscli python-dateutil
    executable: pip3
  ignore_errors: True

- name: Create 00-PreserveFQDN rsyslog setting file
  copy:
    content: |
      # Log FQDN always
      $PreserveFQDN on
    dest: "/etc/rsyslog.d/00-PreserveFQDN.conf"
    owner: root
    group: root
    mode: '0644'