---
# Installing common packages with one task
- name: install required packages using the apt module
  apt:
    name: "{{ item }}"
    update_cache: yes
  with_items:
    - 'python3'
    - 'python3-openssl'
    - 'python3-pip'
    - 'python-pip'
    - 'python-openssl'
    - 'vim-nox'
    - 'tmux'
    - 'nmap'
    - 'tree'
  ignore_errors: True

- name: Install common utils using Pip
  pip:
    name: boto3 awscli python-dateutil
    executable: pip3
  ignore_errors: True