---
- name: Create directory structure for lvm devices
  file:
    path: "{{ item.mount_path }}"
    state: directory
    mode: '755'
  with_items: "{{ lvm_mounts }}"
  when: lvm_mounts is defined

# TODO: add shell commands to replace lvg/lvol ansible modules

#pvcreate /dev/xvdc /dev/xvdd /dev/xvde
#vgcreate splunk_cs /dev/xvdc /dev/xvdd /dev/xvde
#lvcreate -i3 -I4 -l100%FREE -nsplunk_cs splunk_cs

#optional: mkfs.xfs /dev/mapper/splunk_cs-splunk_cs

#- name: Create a volume group
#  lvg:
#    vg: "{{ item.vg }}"
#    pvs: "{{ item.pvs }}"
#  with_items: "{{ lvm_mounts }}"
#  when: lvm_mounts is defined

#- name: Create a logical volume with special options
#  lvol:
#    vg: "{{ item.vg }}"
#    lv: "{{ item.lv }}"
#    size: "{{ item.size }}"
#    opts: "{{ item.opts }}"
#  with_items: "{{ lvm_mounts }}"
#  when: lvm_mounts is defined

- name: Create filesystem on lvm device
  filesystem:
    fstype: "{{ item.fs_type }}"
    dev: "{{ item.device }}"
  with_items: "{{ lvm_mounts }}"
  when: lvm_mounts is defined

- name: Mount filesystem for lvm devices
  mount:
    fstype: "{{ item.fs_type }}"
    src: "{{ item.device }}"
    path: "{{ item.mount_path }}"
    state: mounted
  with_items: "{{ lvm_mounts }}"
  when: lvm_mounts is defined

- name: Create Splunk directory on lvm mounts
  file:
    path: "{{ item.mount_path }}/splunk"
    state: directory
    mode: '750'
  with_items: "{{ lvm_mounts }}"
  when: lvm_mounts is defined

- name: Check for /coldstorage/splunk dir
  stat:
    path: /coldstorage/splunk
  register: path_result


