---
# Configure Splunk Cluster nodes
- name: Include Secrets
  include_vars: "./group_vars/secrets/secrets.yml"

# Sets stage based on the deploy_stage environment variable
- set_fact: stage="{{ vars[deploy_stage] }}"
- set_fact: stage="{{ stage|combine(stage_spec,recursive=True) }}"
  when: use_stage_spec|default(False)

- name: Set facts for systemd servers
  set_fact:
    service_file: "/etc/systemd/system/multi-user.target.wants/Splunkd.service"
    notify_task: "restart splunk systemd"
    tpl_src: "splunk.service.j2"
    tpl_dest: "/etc/systemd/system/multi-user.target.wants/Splunkd.service"
  when: ansible_service_mgr == "systemd"

- name: Set facts for non systemd servers
  set_fact:
    service_file: "/etc/init.d/splunk"
    notify_task: "restart splunk service"
    tpl_src: "splunk.init.j2"
    tpl_dest: "/etc/init.d/splunk"
  when: ansible_service_mgr != "systemd"

- import_tasks: kernel.yml
- import_tasks: mounts.yml
- import_tasks: lvm_mounts.yml
- import_tasks: deploy.yml
- import_tasks: certs.yml
- import_tasks: config.yml
- import_tasks: service.yml
- import_tasks: ds_client.yml
- import_tasks: Splunk_TA_nix.yml