---
- name: Create directory structure
  file:
    path: "{{ item.mount_path }}"
    state: directory
    mode: '755'
  with_items: "{{ disk_mounts }}"

- name: Create disk partition using parted
  parted:
    device: "{{ item.device }}"
    number: 1
    flags: [ lvm ]
    label: gpt
    state: present
  with_items: "{{ disk_mounts }}"

- name: Create filesystem on device
  filesystem:
    fstype: "{{ item.fs_type }}"
    dev: "{{ item.device }}1"
  with_items: "{{ disk_mounts }}"

- name: Mount filesystem
  mount:
    fstype: "{{ item.fs_type }}"
    src: "{{ item.device }}1"
    path: "{{ item.mount_path }}"
    state: mounted
  with_items: "{{ disk_mounts }}"

- name: Create Splunk directory
  file:
    path: "{{ item.mount_path }}/splunk"
    state: directory
    mode: '750'
  with_items: "{{ disk_mounts }}"

- name: Check for /storage/splunk dir
  stat:
    path: /storage/splunk
  register: path_result

- name: Create symlink from /opt/splunk to /storage/splunk
  file:
    src: /storage/splunk
    dest: /opt/splunk
    state: link
  when: path_result.stat.exists == true